service: web-scrapper

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  timeout: 10
  memorySize: 1600
  apiKeys:
    - ${self:service}-${self:provider.stage}

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: false

functions:
  scrape:
    handler: src/handlers/scrape.default
    events:
      - http:
          path: /scrape
          method: post
          private: true

plugins:
  - serverless-offline
  - serverless-webpack